name: keyboard_macos
description: "A new Flutter FFI plugin project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'
resolution: workspace

flutter:
  plugin:
    implements: keyboard
    platforms:
      macos:
        dartPluginClass: KeyboardMacOS
        fileName: keyboard_macos.dart
        ffiPlugin: true

dependencies:
  flutter:
    sdk: flutter
  keyboard_platform_interface:
    path: ../keyboard_platform_interface

dev_dependencies:
  ffi: ^2.1.0
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
